Clarify difference between coq.reduction.{vm,native}.norm
LPCIC/coq-elpi pull request #441
Opened 2023-03-04 23:28 UTC by Blaisorblade

I could be wrong but I guessed from the name and from the source code. Feel free to rephrase as appropriate. cc @jhaag

2023-03-05 07:22 UTC, gares approved these changes

2023-03-05 07:22 UTC, gares requested changes
sorry, I'm ok with the changes, but this file is generated

2023-03-05 23:10 UTC, Blaisorblade commented
Oh right! I've fixed the original but I don't know the regeneration command — I've only found it for `src/coq_elpi_builtins_HOAS.ml` (now documented inline), and `git grep coq-builtin.elpi` finds nothing either. 
(And `make build` fails here since I have Coq 8.16).

2023-03-06 09:07 UTC, gares approved these changes

2023-03-06 09:08 UTC, gares commented
thanks

2023-03-06 09:08 UTC, merged