Add "coq.env.query-extra-dep" external predicate
LPCIC/coq-elpi pull request #525
Opened 2023-10-21 13:36 UTC by phikal

As discussed on [Zulip](https://coq.zulipchat.com/#narrow/stream/253928-Elpi-users-.26-devs/topic/Resolving.20Extra.20Dependencies/near/396087392), this would allow for a predicate to resolve the real path behind a `Extra Dependency`.  As seen in the patch, this just amounts to wrapping `ComExtraDeps.query_extra_dep` in the right way.

2023-10-21 15:03 UTC, gares requested changes
Thanks for this PR.
There are a few things to improve before merging, see the comments.

You should also add a line to the ChangeLog.md file

2023-10-21 15:03 UTC, gares commented on src/coq_elpi_builtins.ml
> +  MLCode(Pred("coq.env.query-extra-dep",
`coq.env` is for accessing the logical environment.
Please move this code just before 
```
-- Datatypes conversions --------------------------------------------
```
maybe in a dedicated section, say `-- Extra Dependency ------------------------`.

Also I'd call it `coq.extra-dep`

2023-10-21 15:19 UTC, phikal commented
Enrico Tassi ***@***.***> writes:

> @gares requested changes on this pull request.
>
> Thanks for this PR.
> There are a few things to improve before merging, see the comments.
>
> You should also add a line to the ChangeLog.md file

Done.

>> @@ -0,0 +1,7 @@
> +From elpi Require Import elpi.
> +
> +From unreleased Extra Dependency "elpi_elaborator.elpi" as elab.
> +
> +Elpi Query lp:{{ coq.env.query-extra-dep "elab" File }}.
> +
> +Fail Elpi Query lp:{{ coq.env.query-extra-dep "foo" File }}.
>
> Please add the test file to _CoqProject.test.
>
> This file is a good test, but the API returns None instead of raising
> `No_clause`, so this will fail once it runs.

I've replaced it with an example that matches (some _).

>> @@ -2325,6 +2325,15 @@ denote the same x as before.|};
>              Some (c, np + na))))))),
>    DocAbove);
>  
> +  MLCode(Pred("coq.env.query-extra-dep",
>
> `coq.env` is for accessing the logical environment.
> Please move this code just before 
> ```
> -- Datatypes conversions --------------------------------------------
> ```
> maybe in a dedicated section, say `-- Extra Dependency ------------------------`.
>
> Also I'd call it `coq.extra-dep`

Fine with me, I've also changed this.

2023-10-21 15:54 UTC, gares requested changes
A few more nits

2023-10-21 15:54 UTC, gares commented on src/coq_elpi_builtins.ml
> +  MLCode(Pred("coq.extra-dep",
Please add an LPDoc line with something like
```
-- Extra Dependencies -------------
```

2023-10-21 15:54 UTC, gares commented on coq-builtin.elpi
> +% [coq.env.query-extra-dep Identifier File Name] Resolve the file name of an
Please regenerate this file

2023-10-21 16:03 UTC, phikal commented
Sorry, missed those.

2023-10-21 22:05 UTC, gares approved these changes

2023-10-22 13:47 UTC, merged

2023-11-05 12:54 UTC, phikal commented
Do you have a schedule when you are planning to publish a release with these changes?

2023-11-05 15:51 UTC, gares commented
Before the end of November