CS app
LPCIC/coq-elpi pull request #577
Opened 2024-01-24 13:43 UTC by Tragicus

Canonical structure hook, with a copy of `evarconv.ml` so that we can make modifications locally and override Coq's current behavior.
N.B. This can evolve easily into an unification hook.
At this time, it is mostly untested.

2024-01-25 20:29 UTC, gares requested changes
Thanks for your contribution!!!

There is file which should be removed (it is generated).
I'd also like `canonical-solution` to be shorted, maybe `cs` or `csolution`.

2024-01-26 08:43 UTC, gares commented on apps/cs/TODOREADME.md
> +pred canonical-solution i:goal-ctx, o:term, o:term.
Fix and rename the file plz

2024-01-26 08:43 UTC, gares commented on apps/cs/tests/test_cs.v
> +canonical-solution _ {{ sort lp:Sol }} {{ nat }} :-
Fix

2024-01-26 09:07 UTC, Tragicus commented
I do not understand what happens with the compilation. There is no "Replace" in the code and yet it magically appears in the .cmt file.

2024-01-26 15:56 UTC, gares approved these changes

2024-01-26 19:27 UTC, merged